root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/ssr"
  cmd = "make theme name=default && go build -o ./bin/ssr ./cmd/ssr"
  delay = 100
  exclude_dir = ["bin", "static"]
  include_ext = ["go", "md", "css"]
  stop_on_error = false

[log]
  main_only = true

[misc]
  clean_on_exit = false
