root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/main.go"
  delay = 100
  exclude_dir = ["tmp"]
  include_ext = ["go"]
  stop_on_error = false

[log]
  main_only = true

[misc]
  clean_on_exit = false
